name: Continuous Integration
on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run Unit Tests
        run: |
          pip install -e .  > /dev/null && pip install pytest pytest-cov > /dev/null && sleep 1
          python -m pytest tests --cov=$(PROJECT_NAME) --cov-config=.coveragerc --cov-fail-under=$(MIN) --cov-report term-missing



